# Generated by Django 4.0.5 on 2022-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0004_alter_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/'),
        ),
    ]
