# Generated by Django 4.0.5 on 2022-06-23 21:33

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('valapp', '0005_alter_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=300)),
                ('contact', models.CharField(blank=True, max_length=300, null=True)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valapp.center')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valapp.profile')),
            ],
        ),
    ]
